feat(sync): add command the pulls all git repos

diff --git a/nvd b/nvd
--- a/nvd
+++ b/nvd
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.1.1 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.1.4 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
@@ -38,6 +38,7 @@ nvd_usage() {
   printf "  %s   Install a Neovim distro\n" "install    "
   printf "  %s   Uninstall a Neovim distro\n" "uninstall  "
   printf "  %s   Start Neovim from an installed distro (default)\n" "run        "
+  printf "  %s   Sync the git repos\n" "sync       "
   echo
 
   # :command.long_usage
@@ -65,7 +66,7 @@ nvd_completions_usage() {
     printf "nvd completions\n"
     echo
 
-    printf "  Generate bash completions\n  Usage: eval \"\$(cli completions)\"\n"
+    printf "  Generate bash completions\n  Usage: eval \"\$(nvd completions)\"\n"
     echo
 
   else
@@ -139,8 +140,10 @@ nvd_install_usage() {
 
     # :command.usage_examples
     printf "%s\n" "Examples:"
-    printf "  cli download example.com\n"
-    printf "  cli download example.com ./output -f\n"
+    printf "  nvd install\n"
+    printf "  nvd install git@github.com:nvim-lua/kickstart.nvim.git\n"
+    printf "  nvd install git@github.com:nvim-lua/kickstart.nvim.git -n kickstart\n"
+    printf "  nvd install git@github.com:nvim-lua/kickstart.nvim.git --name kickstart\n"
     echo
 
   fi
@@ -185,8 +188,8 @@ nvd_uninstall_usage() {
 
     # :command.usage_examples
     printf "%s\n" "Examples:"
-    printf "  cli download example.com\n"
-    printf "  cli download example.com ./output -f\n"
+    printf "  nvd uninstall\n"
+    printf "  nvd uninstall kickstart\n"
     echo
 
   fi
@@ -232,6 +235,43 @@ nvd_run_usage() {
     # :command.usage_examples
     printf "%s\n" "Examples:"
     printf "  nvd run kickstart\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+nvd_sync_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "nvd sync - Sync the git repos\n"
+    echo
+
+  else
+    printf "nvd sync - Sync the git repos\n"
+    echo
+
+  fi
+
+  printf "Alias: s\n"
+  echo
+
+  printf "%s\n" "Usage:"
+  printf "  nvd sync\n"
+  printf "  nvd sync --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_examples
+    printf "%s\n" "Examples:"
+    printf "  nvd sync\n"
     echo
 
   fi
@@ -464,12 +504,32 @@ nvd_run_command() {
   fi
 
   NVIM=$(find "$HOME"/.config/neovim_distros/ -maxdepth 1 -mindepth 1 -type d | sed 's#.*/##' | gum filter)
-  echo "$NVIM"
 
   if [[ $(find "$HOME/.config/neovim_distros/$NVIM" -maxdepth 1 -name "init.lua") == "" ]]; then
       NVIM=$(dirname "$(find "$HOME/.config/neovim_distros/$NVIM" -name "init.lua" | grep "nvim/init.lua")" | sed -n -e 's/^.*neovim_distros\///p')
   fi
+  # yellow "Running as NVIM_APPNAME=neovim_distros/$NVIM nvim"
   NVIM_APPNAME="neovim_distros/$NVIM" nvim "$@"
+
+}
+
+# :command.function
+nvd_sync_command() {
+  # src/sync_command.sh
+  #!/bin/bash
+
+  if ! command -v gum >/dev/null 2>&1; then
+      echo "gum is a required dependency of this scipt. See https://github.com/charmbracelet/gum."
+  fi
+
+  NVIM=$(find "$HOME"/.config/neovim_distros/ -maxdepth 1 -mindepth 1 -type d | sed 's#.*/##')
+
+  while IFS= read -r f; do
+      cd "$HOME/.config/neovim_distros/$f" || continue
+      gum spin --spinner dot --title "Pulling from \"$f\"... ($(git config --get remote.origin.url))" -- git pull
+      green "Successfully pulled from \"$f\"! ($(git config --get remote.origin.url))"
+      cd - >/dev/null || exit 1
+  done <<<"$NVIM"
 
 }
 
@@ -527,6 +587,13 @@ parse_requirements() {
       action="run"
       shift
       nvd_run_parse_requirements "$@"
+      shift $#
+      ;;
+
+    sync | s)
+      action="sync"
+      shift
+      nvd_sync_parse_requirements "$@"
       shift $#
       ;;
 
@@ -775,6 +842,50 @@ nvd_run_parse_requirements() {
 
 }
 
+# :command.parse_requirements
+nvd_sync_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        nvd_sync_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="sync"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
 # :command.initialize
 initialize() {
   version="0.1.0"
@@ -797,6 +908,7 @@ run() {
     "install") nvd_install_command ;;
     "uninstall") nvd_uninstall_command ;;
     "run") nvd_run_command ;;
+    "sync") nvd_sync_command ;;
   esac
 }
 
