chore: add completions

diff --git a/nvd b/nvd
--- a/nvd
+++ b/nvd
@@ -34,9 +34,10 @@ nvd_usage() {
   echo
   # :command.usage_commands
   printf "%s\n" "Commands:"
-  printf "  %s   Install a Neovim distro\n" "install  "
-  printf "  %s   Uninstall a Neovim distro\n" "uninstall"
-  printf "  %s   Start Neovim from an installed distro (default)\n" "run      "
+  printf "  %s   Generate bash completions\n" "completions"
+  printf "  %s   Install a Neovim distro\n" "install    "
+  printf "  %s   Uninstall a Neovim distro\n" "uninstall  "
+  printf "  %s   Start Neovim from an installed distro (default)\n" "run        "
   echo
 
   # :command.long_usage
@@ -53,6 +54,41 @@ nvd_usage() {
 
     # :command.footer
     printf "Depends on Neovim 0.9+\n\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+nvd_completions_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "nvd completions\n"
+    echo
+
+    printf "  Generate bash completions\n  Usage: eval \"\$(cli completions)\"\n"
+    echo
+
+  else
+    printf "nvd completions - Generate bash completions\n"
+    echo
+
+  fi
+
+  printf "Alias: c\n"
+  echo
+
+  printf "%s\n" "Usage:"
+  printf "  nvd completions\n"
+  printf "  nvd completions --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
     echo
 
   fi
@@ -286,6 +322,49 @@ blue_underlined() { print_in_color "\e[4;34m" "$*"; }
 magenta_underlined() { print_in_color "\e[4;35m" "$*"; }
 cyan_underlined() { print_in_color "\e[4;36m" "$*"; }
 
+# src/lib/send_completions.sh
+send_completions() {
+  echo $'# nvd completion                                           -*- shell-script -*-'
+  echo $''
+  echo $'# This bash completions script was generated by'
+  echo $'# completely (https://github.com/dannyben/completely)'
+  echo $'# Modifying it manually is not recommended'
+  echo $''
+  echo $'_nvd_completions_filter() {'
+  echo $'  local words="$1"'
+  echo $'  local cur=${COMP_WORDS[COMP_CWORD]}'
+  echo $'  local result=()'
+  echo $''
+  echo $'  if [[ "${cur:0:1}" == "-" ]]; then'
+  echo $'    echo "$words"'
+  echo $'  '
+  echo $'  else'
+  echo $'    for word in $words; do'
+  echo $'      [[ "${word:0:1}" != "-" ]] && result+=("$word")'
+  echo $'    done'
+  echo $''
+  echo $'    echo "${result[*]}"'
+  echo $''
+  echo $'  fi'
+  echo $'}'
+  echo $''
+  echo $'_nvd_completions() {'
+  echo $'  local cur=${COMP_WORDS[COMP_CWORD]}'
+  echo $'  local compwords=("${COMP_WORDS[@]:1:$COMP_CWORD-1}")'
+  echo $'  local compline="${compwords[*]}"'
+  echo $''
+  echo $'  case "$compline" in'
+  echo $'    *)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_nvd_completions_filter "--help --version -h -v")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'  esac'
+  echo $'} &&'
+  echo $'complete -F _nvd_completions nvd'
+  echo $''
+  echo $'# ex: filetype=sh'
+}
+
 # src/lib/validations/validate_dir_exists.sh
 validate_dir_exists() {
   [[ -d "$1" ]] || echo "must be an existing directory"
@@ -307,6 +386,15 @@ validate_not_empty() {
 }
 
 # :command.command_functions
+# :command.function
+nvd_completions_command() {
+  # src/completions_command.sh
+  #!/bin/bash
+
+  send_completions
+
+}
+
 # :command.function
 nvd_install_command() {
   # src/install_command.sh
@@ -414,6 +502,13 @@ parse_requirements() {
   case $action in
     -*) ;;
 
+    completions | c)
+      action="completions"
+      shift
+      nvd_completions_parse_requirements "$@"
+      shift $#
+      ;;
+
     install | i)
       action="install"
       shift
@@ -448,6 +543,50 @@ parse_requirements() {
       ;;
 
   esac
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+nvd_completions_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        nvd_completions_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="completions"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
@@ -654,6 +793,7 @@ run() {
   parse_requirements "${input[@]}"
 
   case "$action" in
+    "completions") nvd_completions_command ;;
     "install") nvd_install_command ;;
     "uninstall") nvd_uninstall_command ;;
     "run") nvd_run_command ;;
